### PR TITLE
Fix build failure on 32-bit architectures with modern gcc.

### PR DESCRIPTION
**Pull request by kilobyte**
```
conf.c:567:1: error: narrowing conversion of '2240043254u' from
'unsigned int' to 'long int' inside { } [-Wnarrowing]
```
Using a "long" to store unsigned 32-bit values is wrong everywhere: on 32-bit archs new gcc (rightfully) complains about overflow, on 64-bit archs that's merely some waste.

### CODE REVIEW

**Comment by grke** [comment]
Thanks a lot, but I am not making any changes to 1.4.x any more. All changes go to master.

**Comment by kilobyte** [comment]
Should I switch Debian to the 2.0 branch then?  From http://burp.grke.org/ I got an impression that 1.4 is the stable branch and 2.0 is experimental.

(I'm making QA fixes as there's currently no regular maintainer for the package.)

**Comment by grke** [comment]
Hello,
The burp website tries to explain the protocol 1 is good, protocol 2 is experimental.
Burp 2 supports both protocol 1 and 2.

I am working on having a burp-2.0.x 'stable' release. Hopefully it will be the one that comes out at the end of the month.
Personally, I think that the current burp-2.0.46 version is a lot better than 1.4.40. It has much more automated testing, many bugfixes, many more features, etc etc. The thing that you wanted to patch is already fixed there, for example.
But there will be a 2.0.48 at the end of the month.
You should probably wait for me to label a 2.0.x release as 'stable'. Hopefully, that will be 2.0.48.

**Comment by kilobyte** [comment]
Sounds like a plan, I'll wait for 2.0.48 then.  Debian doesn't freeze until January-February anyway, and it's already too late for Ubuntu 16.10.

**Comment by grke** [comment]
Cool, thanks a lot for your effort, it's appreciated.
