### ISSUE TITLE
1.4.32 fails to compile with librsync-1.0.0 due to API change

### ISSUE THREAD

**Issue by ncopa** [grke/burp#273]
The API has changed.

```
backup_phase4_server.c: In function 'int make_rev_sig(const char*, const char*, const char*, int, cntr*)':
backup_phase4_server.c:41:3: error: 'RS_DEFAULT_STRONG_LEN' was not declared in 
this scope
   RS_DEFAULT_STRONG_LEN, NULL, cntr);
   ^
backup_phase2_server.c: In function 'int process_changed_file(sbuf*, sbuf*, cons
t char*, const char*, const char*, int*, cntr*, config*)':
backup_phase2_server.c:486:42: error: 'RS_DEFAULT_STRONG_LEN' was not declared i
n this scope
  if(!(p1b->sigjob=rs_sig_begin(blocklen, RS_DEFAULT_STRONG_LEN)))
                                          ^
Makefile:207: recipe for target 'backup_phase2_server.o' failed
make: *** [backup_phase2_server.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:207: recipe for target 'backup_phase4_server.o' failed
make: *** [backup_phase4_server.o] Error 1
make: Leaving directory '/home/ncopa/aports/testing/burp/src/burp/src'
```
...
```
ccache g++   -c  -Os -fomit-frame-pointer  -I. -I..  -Os -fomit-frame-pointer  rs_buf.c
rs_buf.c: In function 'rs_result rs_sig_gzfile(FILE*, gzFile, FILE*, size_t, size_t, rs_stats_t*, cntr*)':
rs_buf.c:500:49: error: too few arguments to function 'rs_job_t* rs_sig_begin(size_t, size_t, rs_magic_number)'
     job = rs_sig_begin(new_block_len, strong_len);
                                                 ^
In file included from rs_buf.h:29:0,
                 from rs_buf.c:47:
/usr/include/librsync.h:370:11: note: declared here
 rs_job_t *rs_sig_begin(size_t new_block_len,
           ^
Makefile:207: recipe for target 'rs_buf.o' failed
make: *** [rs_buf.o] Error 1
```

some details are provided on a similar bug for duplicity:
https://bugs.launchpad.net/duplicity/+bug/1416344

**Comment by ncopa** [comment]
something like this should work:

```diff
--- ./src/backup_phase2_server.c.orig
+++ ./src/backup_phase2_server.c
@@ -483,7 +483,11 @@
        free(curpath);
 
        blocklen=get_librsync_block_len(cb->endfile);
+#ifdef RS_DEFAULT_STRONG_LEN
        if(!(p1b->sigjob=rs_sig_begin(blocklen, RS_DEFAULT_STRONG_LEN)))
+#else
+       if(!(p1b->sigjob=rs_sig_begin(blocklen, 8, RS_MD4_SIG_MAGIC)))
+#endif
        {
                logp("could not start signature job.\n");
                return -1;
--- ./src/backup_phase4_server.c.orig
+++ ./src/backup_phase4_server.c
@@ -38,7 +38,7 @@
        }
        result=rs_sig_gzfile(dstfp, dstzp, sigp,
                get_librsync_block_len(endfile),
-               RS_DEFAULT_STRONG_LEN, NULL, cntr);
+               8, NULL, cntr);
        gzclose_fp(&dstzp);
        close_fp(&dstfp);
        if(close_fp(&sigp))
--- ./src/rs_buf.c.orig
+++ ./src/rs_buf.c
@@ -497,7 +497,7 @@
     rs_job_t        *job;
     rs_result       r;
 
-    job = rs_sig_begin(new_block_len, strong_len);
+    job = rs_sig_begin(new_block_len, strong_len, RS_MD4_SIG_MAGIC);
     r = rs_whole_gzrun(job, old_file, old_zfile, sig_file, NULL, cntr);
 /*
     if (stats)
```

**Comment by grke** [comment]
Thanks, I have now done something like the above for the next 1.4.x and 2.0.x releases.
